SCMOD-11683: change Digester log level to info
caf-archive/opensuse-tomcat-image pull request #39
Opened 2020-11-16 19:34 UTC by xbreizh

2020-11-16 19:34 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=opensuse-tomcat-image&BRANCH_NAME=SCMOD-11683) to go ahead and create the build...

2020-11-16 19:35 UTC, dermot-hardy commented on opensuse-tomcat-image/src/main/docker/logback.xml
> +    </appender>=info
What does this mean?

2020-11-16 19:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~opensuse-tomcat-image~SCMOD-11683~CI

2020-11-16 20:18 UTC, xbreizh commented on opensuse-tomcat-image/src/main/docker/logback.xml
> +    </appender>=info
typo -> removed

2020-11-16 20:34 UTC, dermot-hardy commented on opensuse-tomcat-image/src/main/docker/logback.xml
> +    <logger name="log4j.logger.org.apache.commons.digester.Digester" level="${CAF_LOG_LEVEL:-INFO}" additivity="false">
Where did you get the logger name?  `log4j.logger.` seems a little strange since I thought we were using Logback rather than Log4J.

2020-11-17 02:04 UTC, dermot-hardy commented on opensuse-tomcat-image/src/main/docker/logback.xml
> +    <logger name="log4j.logger.org.apache.commons.digester.Digester" level="${CAF_LOG_LEVEL:-INFO}" additivity="false">
I notice you've removed the `log4j.logger.` prefix now.  Did you verify that was incorrect?

2020-11-17 18:15 UTC, dermot-hardy requested changes
I don't understand how this could possibly change anything.  (In fairness I don't understand the `org.apache.catalina` one already listed there either.)  Regardless I need that demo'ed to me.

2020-11-17 20:42 UTC, closed without merging