Simplify by removing tomcat user stuff and symbolic link
caf-archive/opensuse-tomcat-image pull request #4
Opened 2017-10-26 19:19 UTC by dermot-hardy

Is there any problem with just doing this?  What is the permissions issue that caused that tomcat user/group stuff to be introduced?

2017-10-26 19:53 UTC, rob-duewer commented
Best practice for any tomcat instance is to run it not as the root user, but a configured one. user tomcat group tomcat is traditional.  Since it is not difficult to do, I would expect us to follow that standard best practice inside the container also.  It's less critical than when running outside of a container of course becasue of the sandbox nature; but if it isn't hard to do and keeps the container internals equal to bare metal best practices; in my opinion, it should still be followed.

As @bhagyashreen noted in email, she was moving the directory to the shared name of tomcat, instead of using a symlink which is why she applied permissions after the mv.  But when changing to symlink (which is the more traditional model which we discussed before), just apply those permissions first and then create the symlink instead of vice versa.

2017-10-26 20:03 UTC, rob-duewer requested changes
I would keep the ownership to tomcat if possible.  One of the downsides about setting up the dir in the separate build image and copying them in directly is you won't be able to preset up those perms and have them brought over with the copy.

2017-10-26 21:19 UTC, dermot-hardy commented
She said she did those steps because she was getting a permissions error - not because of anything to do with best practice.  If the real reason was to meet a best practice, then that is fine, but let's check if it has actually been met, because presumably it is not solely about file ownership but also about who the service is run as, and I don't see anything which means the service will not be run as `root`, which I'm guessing defeats the best practice.  Also as I pointed out in the e-mail I'm not convinced the file ownership has actually been changed.

2017-10-26 22:14 UTC, dermot-hardy commented
I just took a look a few of the official Tomcat images on DockerHub and they don't appear to be following this practice.  I looked back in their history and discovered this --> https://github.com/docker-library/tomcat/pull/6.

2017-10-26 22:22 UTC, dermot-hardy commented
Of particular interest is that they previously had a `USER` statement in their Dockerfile.  Presumably this is required so that the service actually runs as the tomcat user, and without it just changing the file permissions is pointless.  (And of course I'm ignoring the fact that I don't think the `chown` statement is doing what is intended because of the symbolic link).

2017-10-26 22:54 UTC, dermot-hardy commented
This is an interesting image that we might be able to steal some ideas from:
https://github.com/Unidata/tomcat-docker

It is based on the official Tomcat image but then makes changes to attempt to security harden it.  It does seem to include the tomcat user/group permissions change, but then it also includes an `entrypoint.sh` script so that Tomcat actually runs as that user.

2017-10-27 15:25 UTC, rob-duewer commented
Yes, that unidata example is doing quite a bit of what I'd normally do as a best practice for a bare metal TC. But there's quite a bit extra there that you don't need to do on baremetal, apparently becasue sudo and su aren't quite playing properly when they're container outboard volumes.  They are also doing a bit more fanciness since they're trying to avoid having to add platform certificate management (which we already have in ours) and wget (which we're avoiding needing too).

So I think for us, I would create the group and owner and set the directory owner them to them still (before setting the symlink or after the copy if we're just copying it directly to the name).  For a container consumer that is just directly launching catalina as root, no harm no foul.  It cost us one line and one layer.  But for one that uses a launch script to execute their app, which I expect all of them to do down the road since it makes calling the cert loading scripts (and eventually TLS prep scripts) way easier; that can call the catalina script with a su tomcat prefix.  Since we're not doing any external volume stuff for these and have logging all redirected now to stdin/out; I don't think any of the complexity they had to add to use gosu is needed for us.  At least worth a skunkworks go at that to see if my hunch is right.

If not, then I'm ok with leaving and running it as root inside the container only, pretty much all our other containers are doing this.   But my preference remains that if possible, we should try and follow all the same baremetal rules for a component inside containers, if there are not too many hoops to jump through. :)

2017-10-27 18:01 UTC, dermot-hardy commented
OK - I think we can all agree that this is not right as it is?  I propose that we merge this change and then circle back to this after we have dealt with the SSL issues.  Is that fair enough?

2017-10-27 21:56 UTC, rob-duewer commented
I'm OK with going with operating as root from /usr/share/tomcat/ for the time being.  And revisiting later apply proper user control of the inner process later on.  Cheers!

2017-10-30 16:22 UTC, merged

2018-01-08 10:30 UTC, dermot-hardy commented
Note that [CAF-4050](https://jira.autonomy.com/browse/CAF-4050) has been raised for this.